# https://docs.gitlab.com/ee/ci/yaml/index.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS || $CI_COMMIT_TAG
      when: never
    - when: always

stages:
 - lint
 - version
 - docker-compose
 - docker-images
 - docker-registry
 - release

commit-lint:
  stage: lint
  image: node
  script:
    - npm i --save @commitlint/config-conventional
    - git fetch https://gitlab.com/isard/isardvdi.git main
    - npx commitlint -x "@commitlint/config-conventional" --from=$(git merge-base HEAD FETCH_HEAD)

version:
  stage: version
  image: node
  rules:
    # semantic-release checks repository write access and we cannot use
    # GITLAB_TOKEN in unprotected branches due to security reasons.
    # https://github.com/semantic-release/semantic-release/issues/2207
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm install -g semantic-release @semantic-release/exec conventional-changelog-conventionalcommits
    - cp releaserc.version.yml .releaserc.yml
    - semantic-release --dry-run --branches $CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - .VERSION

changelog-preview:
  # This is a workarround to show changelog preview without semantic-release
  # see comment in job "version".
  stage: version
  image: node
  script:
    - npm install -g conventional-changelog-cli conventional-changelog-conventionalcommits
    - conventional-changelog -p conventionalcommits -o CHANGELOG.md
    - cat CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md

check-python:
  stage: lint
  image: python:3.10-bullseye
  script:
    - pip install isort black
    - isort --check .
    - black --check .

docker-compose:
  image: docker:latest
  stage: docker-compose
  services:
    - docker:dind
  script:
    - test "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" -a ! -e ".VERSION" && exit 0
    - apk add bash git docker-compose
    # Use docker compose < 1.27 to avoid depends_on issue
    # https://github.com/isard-vdi/isard/issues/390
    - apk add py3-pip
    - pip install docker-compose~=1.26.0
    - cp isardvdi.cfg.example isardvdi.cfg
    - echo "DOCKER_IMAGE_PREFIX=${CI_REGISTRY_IMAGE}/" >> isardvdi.cfg
    - echo "DOCKER_IMAGE_TAG=$CI_COMMIT_REF_SLUG" >> isardvdi.cfg
    - cp isardvdi.cfg isardvdi.build.cfg
    - echo "USAGE=build" >> isardvdi.build.cfg
    - cp isardvdi.build.cfg isardvdi.video-standalone.build.cfg
    - echo "FLAVOUR=video-standalone" >> isardvdi.video-standalone.build.cfg
    - cp isardvdi.build.cfg isardvdi.toolbox.build.cfg
    - echo "FLAVOUR=toolbox" >> isardvdi.toolbox.build.cfg
    - ./build.sh
  artifacts:
    paths:
      - docker-compose*.yml

docker-image:
  image: docker:latest
  stage: docker-images
  services:
    - docker:dind
  parallel:
    matrix:
      - DOCKER_COMPOSE: build
        IMAGE:
          - api
          - authentication
          - engine
          - grafana
          - guac
          - hypervisor
          - portal
          - squid
          - static
          - stats
          - vpn
          - webapp
          - websockify
      - DOCKER_COMPOSE: video-standalone.build
        IMAGE: video
      - DOCKER_COMPOSE: toolbox.build
        IMAGE: toolbox
  script:
    - test "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" -a ! -e ".VERSION" && exit 0
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - apk add git docker-compose
    - git submodule update --init --recursive --remote
    - docker-compose -f docker-compose.$DOCKER_COMPOSE.yml build isard-$IMAGE
    - docker tag $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE/$IMAGE:git-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$IMAGE:git-$CI_COMMIT_SHORT_SHA

docker-tag:
  stage: docker-registry
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  parallel:
    matrix:
      - IMAGE:
          - api
          - authentication
          - engine
          - grafana
          - guac
          - hypervisor
          - portal
          - squid
          - static
          - stats
          - vpn
          - webapp
          - websockify
          - video
          - toolbox
  script:
    - test "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" -a ! -e ".VERSION" && exit 0
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - crane tag $CI_REGISTRY_IMAGE/$IMAGE:git-$CI_COMMIT_SHORT_SHA $CI_COMMIT_REF_SLUG
    - test ! -e ".VERSION" && exit 0
    - crane tag $CI_REGISTRY_IMAGE/$IMAGE:git-$CI_COMMIT_SHORT_SHA v$(cat .VERSION | tr '.' '-')

release:
  stage: release
  image: node
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - test ! -e ".VERSION" && exit 0
    - 'sed -i "s/^\(\s*DOCKER_IMAGE_TAG: \)$CI_DEFAULT_BRANCH$/\1v$(cat .VERSION | tr "." "-")/" docker-compose*.yml'
    - npm install -g semantic-release @semantic-release/gitlab conventional-changelog-conventionalcommits
    - cp releaserc.release.yml .releaserc.yml
    - semantic-release --branches $CI_DEFAULT_BRANCH
