apiVersion: v2
name: isard-desktopbuilder
description: A Helm chart for the Desktop Builder Isard microservice. You probably don't want to install this but 'isard'
type: application
version: 0.1.0
appVersion: 3.0.0
