[influxdb]
host = "testing-storage-default-web.europe-west4-b.c.isard-vdi20210205.internal"
token = "9eFW/Qi29hL3hFGUP8wIGH89XKCH8s1k0il44GCRF2g="
bucket = "isardvdi-go"

[collectors]
  [collectors.hypervisor]
  enable = true

  [collectors.system]
  enable = true