version: "3.5"
services:
  isard-api:
    container_name: isard-api
    image: ${DOCKER_IMAGE_PREFIX}api:${DOCKER_IMAGE_TAG:-latest}
    logging:
      options:
        max-size: "100m"
    ports:
      - "7039:7039"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET}.10
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
