version: '3.5'
services:
  isard-api:
    container_name: isard-api
    image: ${DOCKER_IMAGE_PREFIX}api:${DOCKER_IMAGE_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.10
    volumes:
      - /opt/isard/sshkeys/:/sshkeys:rw
      - /opt/isard/certs/viewers:/viewers:ro
    env_file:
      - .env
