version: '3.5'
services:
  isard-backend:
    container_name: isard-backend
    image: ${DOCKER_IMAGE_PREFIX}backend:${DOCKER_IMAGE_TAG:-latest}
    logging:
      options:
        max-size: "100m"
    # ports:
    #   - "127.0.0.1:1312:1312"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET}.11
    restart: unless-stopped
    volumes:
      - "/opt/isard/backend/keys:/keys"
      - "/opt/isard/backend/metadata:/metadata"
    env_file:
      - .env

  isard-redis:
    container_name: isard-redis
    image: redis:6-alpine
    logging:
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET}.12
    restart: unless-stopped
    volumes:
      - "/opt/isard/redis:/data"
