version: '3.5'
services:
  isard-db:
    container_name: isard-db
    image: ${DOCKER_IMAGE_PREFIX}db:${DOCKER_IMAGE_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.13
    volumes:
    - /opt/isard/database:/data:rw
