version: '3.5'
services:
  isard-engine:
    container_name: isard-engine
    image: ${DOCKER_IMAGE_PREFIX}engine:${DOCKER_IMAGE_TAG-latest}
    logging:
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.14
    volumes:
      - /opt/isard/certs/viewers:/certs:rw
      - /opt/isard/sshkeys:/root/.ssh:rw
    depends_on:
      - isard-db
    env_file:
      - .env
