version: '3.5'
services:
  isard-grafana:
    container_name: isard-grafana
    image: ${DOCKER_IMAGE_PREFIX}grafana:${DOCKER_IMAGE_TAG-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - INFLUXDB_ADDRESS=${INFLUXDB_ADDRESS:-http://isard-influxdb:8086}
      - LOKI_ADDRESS=${LOKI_ADDRESS:-http://isard-loki:3100}

  isard-influxdb:
    image: ${DOCKER_IMAGE_PREFIX}influxdb:${DOCKER_IMAGE_TAG-latest}
    container_name: isard-influxdb
    volumes:
      - ${STATS_DIRECTORY:-/opt/isard/stats}/influxdb/data:/var/lib/influxdb2:rw
      - ${STATS_DIRECTORY:-/opt/isard/stats}/influxdb/config:/etc/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${WEBAPP_ADMIN_PWD}
      - DOCKER_INFLUXDB_INIT_ORG=isardvdi
      - DOCKER_INFLUXDB_INIT_BUCKET=isardvdi
      - DOCKER_INFLUXDB_INIT_RETENTION=54w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN_SECRET}
      - STATS_GLANCES_DATA_RETENTION=${STATS_GLANCES_DATA_RETENTION:-2w}
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.12
    restart: unless-stopped

  isard-loki:
    container_name: isard-loki
    image: grafana/loki:2.4.1
    user: root
    volumes:
      - /opt/isard/stats/loki:/data
      - ${BUILD_ROOT_PATH}/docker/loki/config.yaml:/etc/loki/local-config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.67
    restart: unless-stopped
    env_file:
      - .env

  isard-promtail:
    container_name: isard-promtail
    image: grafana/promtail:2.4.1
    volumes:
      - ${BUILD_ROOT_PATH}/docker/promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.69
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file:
      - .env
    environment:
      - LOKI_ADDRESS=${LOKI_ADDRESS:-http://isard-loki:3100}
