version: '3.5'
services:
  isard-guac:
    container_name: isard-guac
    image: ${DOCKER_IMAGE_PREFIX}guac:${DOCKER_IMAGE_TAG-latest}
    environment:
      GUACD_ADDR: isard-vpn:4822
      API_ISARDVDI_SECRET: ${API_ISARDVDI_SECRET}
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.18.255}.16
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
