version: '3.5'
services:
  isard-guac:
    container_name: isard-guac
    image: ${DOCKER_IMAGE_PREFIX}guac:${DOCKER_IMAGE_TAG-latest}
    environment:
      GUACD_ADDR: isard-vpn:4822
      API_ISARDVDI_SECRET: ${API_ISARDVDI_SECRET}
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.16

  isard-rdpgw:
    container_name: isard-rdpgw
    image: ${DOCKER_IMAGE_PREFIX}rdpgw:${DOCKER_IMAGE_TAG-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    env_file:
      - .env
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.22
