version: '3.5'
services:
  isard-hypervisor:
    container_name: isard-hypervisor
    image: ${DOCKER_IMAGE_PREFIX}hypervisor:${DOCKER_IMAGE_TAG-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.17
    privileged: true
    volumes:
      - /opt/isard:/isard:rw
      - /opt/isard-local/sockets/:/var/run/libvirt/
      - /dev/vfio:/dev/vfio
      - ${BUILD_ROOT_PATH}/docker/hypervisor/src/ovs:/src/ovs
    env_file:
      - .env
    environment:
      HYPER_ID:
      HYPER_ENABLED:
      DOMAIN:
      VIDEO_DOMAIN:
      VIEWER_SPICE:
      VIEWER_BROWSER:
