version: '3.5'
services:
  isard-portal:
    container_name: isard-portal
    image: ${DOCKER_IMAGE_PREFIX}portal:${DOCKER_IMAGE_TAG-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    cap_add:
    - NET_ADMIN    
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.18
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 443
        target: 443
        mode: host
    volumes:
      - /opt/isard/certs/letsencrypt:/etc/letsencrypt:rw
      - /opt/isard/certs/default:/certs:rw
    env_file:
      - .env
