version: '3.5'
services:
  isard-scheduler:
    container_name: isard-scheduler
    image: ${DOCKER_IMAGE_PREFIX}scheduler:${DOCKER_IMAGE_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - /opt/isard/backups:/src/backups:rw
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.24
    environment:
      LOG_LEVEL:
      RETHINKDB_HOST:
      RETHINKDB_PORT:
      RETHINKDB_DB:
      API_ISARDVDI_SECRET:
      USAGE:
