version: '3.5'
services:
  isard-scheduler:
    container_name: isard-scheduler
    ports:
      - "5001:5000"
    volumes:
    - ${BUILD_ROOT_PATH}/scheduler/src:/src
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: scheduler/docker/Dockerfile
      target: production
