version: "3.5"
services:
  isard-squid:
    container_name: isard-squid
    image: ${DOCKER_IMAGE_PREFIX}squid:${DOCKER_IMAGE_TAG-latest}
    logging:
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET}.19
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    env_file:
      - .env
