version: '3.5'
services:
  isard-stats:
    volumes:
      - ${BUILD_ROOT_PATH}/docker/stats/src:/src:rw
    # environment:
    #   - STATS_HYP_HOSTNAME=isard-hypervisor
    #   - STATS_HYP_USER=root
    #   - STATS_HYP_PORT=22
