version: "3.5"
services:
  # This is kept until isard-stats is fixed, then it will be comented out
  # isard-stats:
  #   image: ${DOCKER_IMAGE_PREFIX}stats:${DOCKER_IMAGE_TAG-latest}
  #   container_name: isard-stats
  #   logging:
  #     options:
  #       max-size: "100m"
  #   env_file:
  #     - .env
  #   networks:
  #     isard-network: {}
  #   restart: unless-stopped
  #   depends_on:
  #     - isard-hypervisor

  isard-stats-go:
    image: ${DOCKER_IMAGE_PREFIX}stats-go:${DOCKER_IMAGE_TAG-latest}
    container_name: isard-stats-go
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped
    networks:
      isard-network: {}
    env_file:
      - .env
    environment:
      - FLAVOUR=${FLAVOUR:-all-in-one}

  isard-stats-glances:
    image: ${DOCKER_IMAGE_PREFIX}stats-glances:${DOCKER_IMAGE_TAG-latest}
    container_name: isard-stats-glances
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/isard:/opt/isard:ro
    env_file:
      - .env
