version: '3.5'
services:
  isard-static:
    container_name: isard-static
    image: ${DOCKER_IMAGE_PREFIX}static:${DOCKER_IMAGE_TAG-latest}
    logging:
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.20
    volumes:
      - /opt/isard/frontend/custom:/usr/share/nginx/html/custom:ro
