version: "3.5"
services:
  # This is kept until isard-stats is fixed, then it will be comented out
  # isard-stats:
  #   image: ${DOCKER_IMAGE_PREFIX}stats:${DOCKER_IMAGE_TAG-latest}
  #   container_name: isard-stats
  #   logging:
  #     options:
  #       max-size: "100m"
  #   env_file:
  #     - .env
  #   networks:
  #     isard-network: {}
  #   restart: "no"
  #   depends_on:
  #     - isard-hypervisor

  isard-stats-go:
    image: ${DOCKER_IMAGE_PREFIX}stats-go:${DOCKER_IMAGE_TAG-latest}
    container_name: isard-stats-go
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    restart: "no"
    networks:
      isard-network: {}
    env_file:
      - .env
    environment:
      - FLAVOUR=${FLAVOUR:-all-in-one}

  isard-stats-glances:
    image: ${DOCKER_IMAGE_PREFIX}stats-glances:${DOCKER_IMAGE_TAG-latest}
    container_name: isard-stats-glances
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    restart: "no"
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/isard:/opt/isard:ro
      - /opt/isard/templates:/opt/isard/templates:ro
      - /opt/isard/groups:/opt/isard/groups:ro
      - /opt/isard/media:/opt/isard/media:ro
      - /:/disk:ro
    env_file:
      - .env

  isard-promtail:
    container_name: isard-promtail
    image: grafana/promtail:2.4.1
    volumes:
      - ${BUILD_ROOT_PATH}/docker/promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.69
    restart: "no"
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file:
      - .env
    environment:
      - LOKI_ADDRESS=${LOKI_ADDRESS:-http://isard-loki:3100}
