version: '3.5'
services:
  isard-video:
    container_name: isard-video
    image: ${DOCKER_IMAGE_PREFIX}video:${DOCKER_IMAGE_TAG-latest}
    logging:
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET}.22
    ports:
      - published: 80
        target: 80
      - published: ${VIDEO_PORT}
        target: 443
      # - published: ${VIDEO_STATS_PORT}
      #   target: 8888
    restart: unless-stopped
    volumes:
      - /opt/isard/certs/letsencrypt:/etc/letsencrypt:rw
      - /opt/isard/certs/default/${HOSTNAME}:/certs:rw
    env_file:
      - .env
