version: '3.5'
services:
  isard-websockify:
    container_name: isard-websockify
    image: ${DOCKER_IMAGE_PREFIX}websockify:${DOCKER_IMAGE_TAG-latest}
    logging:
      options:
        max-size: "100m"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.27
    restart: unless-stopped
    env_file:
      - .env
